apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-auth
  template:
    metadata:
      labels:
        app: jwt-auth
    spec:
      containers:
        - name: jwt-auth
          image: 192.168.10.2:30000/jwt_auth:latest
          ports:
            - containerPort: 8013
---
apiVersion: v1
kind: Service
metadata:
  name: jwt-auth
spec:
  selector:
    app: jwt-auth
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
  type: LoadBalancer